<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Booqr.Logic\Booqr.Logic.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Pages\Facilities\" />
    <Folder Include="Pages\Dashboard\" />
    <Folder Include="Pages\Reservations\" />
  </ItemGroup>

</Project>
